const PRODUCTS = [
  {
    id: 1,
    name: "Wireless Noise-Cancelling Headphones",
    price: 79.99,
    originalPrice: 99.99,
    category: "Electronics",
    description: "Immerse yourself in premium sound with active noise cancellation, 30-hour battery life, and foldable over-ear design. Compatible with all Bluetooth devices and includes a 3.5mm cable for wired use.",
    rating: 4.5,
    reviews: 128,
    inStock: true,
    emoji: "🎧",
    badge: "sale"
  },
  {
    id: 2,
    name: "Smart Watch Pro",
    price: 149.99,
    originalPrice: null,
    category: "Electronics",
    description: "Track your fitness, monitor your health, and stay connected with this feature-rich smartwatch. Features GPS, heart rate monitor, sleep tracking, 7-day battery life, and 50m water resistance.",
    rating: 4.3,
    reviews: 89,
    inStock: true,
    emoji: "⌚",
    badge: "new"
  },
  {
    id: 3,
    name: "Portable Bluetooth Speaker",
    price: 49.99,
    originalPrice: 64.99,
    category: "Electronics",
    description: "360-degree surround sound with deep bass in a compact, rugged design. IPX7 waterproof, 12-hour playtime, and built-in microphone for hands-free calls. Perfect for outdoors.",
    rating: 4.6,
    reviews: 215,
    inStock: true,
    emoji: "🔊",
    badge: "sale"
  },
  {
    id: 4,
    name: "4K Ultra HD Webcam",
    price: 89.99,
    originalPrice: null,
    category: "Electronics",
    description: "Crystal-clear 4K video at 30fps with auto-focus, low-light correction, and a built-in stereo microphone. Plug-and-play USB-C setup compatible with all major video conferencing platforms.",
    rating: 4.4,
    reviews: 63,
    inStock: true,
    emoji: "📷",
    badge: null
  },
  {
    id: 5,
    name: "Classic Cotton T-Shirt",
    price: 24.99,
    originalPrice: null,
    category: "Clothing",
    description: "Made from 100% GOTS-certified organic cotton, this relaxed unisex tee is pre-shrunk and machine washable. Available in 8 colours, it's the wardrobe essential you'll reach for every day.",
    rating: 4.2,
    reviews: 312,
    inStock: true,
    emoji: "👕",
    badge: null
  },
  {
    id: 6,
    name: "Slim Fit Stretch Jeans",
    price: 59.99,
    originalPrice: 79.99,
    category: "Clothing",
    description: "Premium denim with 2% elastane for all-day comfort. Classic 5-pocket design with a modern tapered leg and mid-rise waist. Machine washable and built to last.",
    rating: 4.4,
    reviews: 176,
    inStock: true,
    emoji: "👖",
    badge: "sale"
  },
  {
    id: 7,
    name: "Fleece-Lined Hoodie",
    price: 44.99,
    originalPrice: null,
    category: "Clothing",
    description: "Super-soft French terry fleece hoodie with a cozy lined interior, kangaroo pocket, and adjustable drawstring. Lightweight enough to layer and warm enough to stand alone.",
    rating: 4.7,
    reviews: 94,
    inStock: false,
    emoji: "🧥",
    badge: null
  },
  {
    id: 8,
    name: "Running Shoes – CloudFoam",
    price: 84.99,
    originalPrice: 109.99,
    category: "Clothing",
    description: "Engineered mesh upper with CloudFoam cushioning for responsive energy return. Breathable, lightweight, and built for road running or everyday wear. Available in sizes 6–13.",
    rating: 4.6,
    reviews: 241,
    inStock: true,
    emoji: "👟",
    badge: "sale"
  },
  {
    id: 9,
    name: "Insulated Water Bottle 1L",
    price: 19.99,
    originalPrice: 24.99,
    category: "Home & Kitchen",
    description: "Double-wall vacuum insulation keeps drinks cold for 24 hours or hot for 12 hours. BPA-free, leak-proof lid, and scratch-resistant powder coat finish. Fits most car cup holders.",
    rating: 4.8,
    reviews: 527,
    inStock: true,
    emoji: "🫙",
    badge: "sale"
  },
  {
    id: 10,
    name: "Non-Stick Cookware Set (10pc)",
    price: 89.99,
    originalPrice: 119.99,
    category: "Home & Kitchen",
    description: "PFOA-free non-stick coating on heavy-gauge aluminium for even heat distribution. Includes 2 frying pans, 2 sauce pans, a sauté pan, and matching lids. Compatible with all stovetops including induction.",
    rating: 4.3,
    reviews: 143,
    inStock: true,
    emoji: "🍳",
    badge: "sale"
  },
  {
    id: 11,
    name: "Programmable Coffee Maker",
    price: 39.99,
    originalPrice: null,
    category: "Home & Kitchen",
    description: "Brew up to 12 cups with adjustable brew strength, a 24-hour programmable timer, and auto-shutoff. Pause-and-pour carafe and a permanent gold-tone filter included.",
    rating: 4.1,
    reviews: 88,
    inStock: true,
    emoji: "☕",
    badge: "new"
  },
  {
    id: 12,
    name: "Ergonomic Office Chair",
    price: 249.99,
    originalPrice: 299.99,
    category: "Home & Kitchen",
    description: "Lumbar support, adjustable armrests, seat height, and tilt tension in a breathable mesh back design. Supports up to 120 kg. Perfect for long work-from-home sessions.",
    rating: 4.5,
    reviews: 192,
    inStock: true,
    emoji: "🪑",
    badge: "sale"
  },
  {
    id: 13,
    name: "The Art of Clean Code",
    price: 29.99,
    originalPrice: null,
    category: "Books",
    description: "A practical guide to writing maintainable, readable, and efficient software. Covers SOLID principles, refactoring patterns, and real-world case studies for developers at every level.",
    rating: 4.9,
    reviews: 421,
    inStock: true,
    emoji: "📘",
    badge: null
  },
  {
    id: 14,
    name: "Data Analytics Fundamentals",
    price: 34.99,
    originalPrice: 44.99,
    category: "Books",
    description: "A comprehensive introduction to data collection, cleaning, analysis, and visualisation. Includes hands-on exercises using Python and real-world datasets from business and finance.",
    rating: 4.6,
    reviews: 198,
    inStock: true,
    emoji: "📊",
    badge: "sale"
  },
  {
    id: 15,
    name: "Digital Marketing Mastery",
    price: 27.99,
    originalPrice: null,
    category: "Books",
    description: "Learn to design and execute high-ROI digital marketing campaigns. Covers SEO, paid search, email, social media, content strategy, and analytics — with templates you can use immediately.",
    rating: 4.4,
    reviews: 167,
    inStock: true,
    emoji: "📱",
    badge: null
  },
  {
    id: 16,
    name: "UX Design Principles",
    price: 32.99,
    originalPrice: null,
    category: "Books",
    description: "From research and wireframing to prototyping and usability testing — this definitive guide covers the full UX process. Packed with real project examples and actionable frameworks.",
    rating: 4.7,
    reviews: 309,
    inStock: false,
    emoji: "🎨",
    badge: null
  }
];

const CATEGORIES = [...new Set(PRODUCTS.map(p => p.category))];
